export enum ActionConstants {
  SET_CALC_ENTITY = "SET_CALC_ENTITY",
  SET_IS_INVALID = "SET_IS_INVALID",
  GET_CHARTLIST = "GET_CHARTLIST",
  SET_CHARTLIST = "SET_CHARTLIST",

  SET_LOAN_REASON_VALUE = "SET_LOAN_REASON_VALUE",
  SET_LOAN_REASON_LIST = "SET_LOAN_REASON_LIST",
  SET_HAS_SALARY_CARD = "SET_HAS_SALARY_CARD",
  SET_HAS_SALARY_CARD_SELECTED = "SET_HAS_SALARY_CARD_SELECTED",
  SET_HOUSE_COST = "SET_HOUSE_COST",
  SET_HOUSE_COST_VALUE = "SET_HOUSE_COST_VALUE",
  SET_INITIAL_PAYMENT = "SET_INITIAL_PAYMENT",
  SET_INITIAL_PAYMENT_VALUE = "SET_INITIAL_PAYMENT_VALUE",
  SET_LOAN_PERIOD = "SET_LOAN_PERIOD",
  SET_LOAN_PERIOD_VALUE = "SET_LOAN_PERIOD_VALUE"
}
