version: 2.1

orbs:
  docker: circleci/docker@0.5.13

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: cimg/node:16.13.0
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'yarn global add yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: gql-types
          command: yarn graphql-codegen
      - run:
          name: test
          command: yarn test:unit

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a mortgage-calculator-react web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a mortgage-calculator-react web

workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      - build:
          requires:
            - run_tests
